name: Events Demo 1
on: 
  pull_request:
    types: 
      - opened
    branches: 
      - main # Matches the main branch
      - 'dev-*' # Matches any branch starting with 'dev-'
      - 'feat/**' # Matches any branch starting with 'feat/'
  workflow_dispatch: 
  push:
    branches: 
      - main # Matches the main branch
      - 'dev-*' # Matches any branch starting with 'dev-'
      - 'feat/**' # Matches any branch starting with 'feat/'
    paths-ignore: 
      - '.github/workflows/*' # Ignore changes to this workflow file
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."